# Generated by Django 4.1.5 on 2023-01-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='published_at',
            field=models.DateTimeField(verbose_name='Время публикации'),
        ),
    ]
