# Generated by Django 4.1.5 on 2023-01-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='date',
            field=models.DateField(verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='date',
            name='published_at',
            field=models.DateField(verbose_name='Время публикации'),
        ),
    ]
