# Generated by Django 4.1.5 on 2023-01-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_category_date_alter_date_published_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='date',
            name='published_at',
            field=models.DateTimeField(verbose_name='Время публикации'),
        ),
    ]
