# Generated by Django 4.1.5 on 2023-01-12 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_delete_category_alter_date_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='decemberDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decDay', models.DateTimeField(db_index=True, verbose_name='Дата публикации')),
            ],
        ),
        migrations.AddField(
            model_name='date',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='polls.decemberday'),
        ),
    ]
