# Generated by Django 4.1.5 on 2023-01-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_decemberday_date_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='published_at',
            field=models.DateField(verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='decemberday',
            name='decDay',
            field=models.DateField(db_index=True, verbose_name='Дата публикации'),
        ),
    ]
