# Generated by Django 4.1.5 on 2023-01-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_date_published_at_alter_decemberday_decday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mein',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
